version: '3.8'

services:
  backend:
    build:
      context: Backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://Konpid:Konpid@konpidmongodb.r4m7yyl.mongodb.net/
      - JWT_SECRET=MVYNLAVULXBPGZWLLKYBUWYVQLJAPTTLKPHALSF
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30

  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY=
      - MONGO_URI=mongodb+srv://Konpid:Konpid@konpidmongodb.r4m7yyl.mongodb.net/
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://backend:5000
      - NEXT_PUBLIC_BASE_PATH=/src/app
      - SMTP_PASSWORD=fdve regs jpuj xhsr
      - SMTP_EMAIL=dentistbookingnoti@gmail.com
